apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: machines.cluster.k8s.io
  labels:
    local-testing: "true"
spec:
  group: cluster.k8s.io
  version: v1alpha1
  scope: Namespaced
  names:
    kind: Machine
    plural: machines
  additionalPrinterColumns:
  - name: Provider
    type: string
    JSONPath: .spec.providerSpec.value.cloudProvider
  - name: OS
    type: string
    JSONPath: .spec.providerSpec.value.operatingSystem
  - name: Address
    type: string
    JSONPath: .status.addresses[0].address
  - name: Age
    type: date
    JSONPath: .metadata.creationTimestamp

---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: machinesets.cluster.k8s.io
  labels:
    local-testing: "true"
spec:
  group: cluster.k8s.io
  version: v1alpha1
  scope: Namespaced
  names:
    kind: MachineSet
    plural: machinesets
  subresources:
     # status enables the status subresource.
     status: {}
  additionalPrinterColumns:
  - name: Replicas
    type: integer
    JSONPath: .spec.replicas
  - name: Provider
    type: string
    JSONPath: .spec.template.spec.providerSpec.value.cloudProvider
  - name: OS
    type: string
    JSONPath: .spec.template.spec.providerSpec.value.operatingSystem
  - name: Age
    type: date
    JSONPath: .metadata.creationTimestamp
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: machinedeployments.cluster.k8s.io
  labels:
    local-testing: "true"
spec:
  group: cluster.k8s.io
  version: v1alpha1
  scope: Namespaced
  names:
    kind: MachineDeployment
    plural: machinedeployments
  subresources:
     # status enables the status subresource.
     status: {}
  additionalPrinterColumns:
  - name: Replicas
    type: integer
    JSONPath: .spec.replicas
  - name: Provider
    type: string
    JSONPath: .spec.template.spec.providerSpec.value.cloudProvider
  - name: OS
    type: string
    JSONPath: .spec.template.spec.providerSpec.value.operatingSystem
  - name: Age
    type: date
    JSONPath: .metadata.creationTimestamp
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: clusters.cluster.k8s.io
  labels:
    local-testing: "true"
spec:
  group: cluster.k8s.io
  version: v1alpha1
  scope: Namespaced
  names:
    kind: Cluster
    plural: clusters
  subresources:
     # status enables the status subresource.
     status: {}
