apiVersion: "cluster.k8s.io/v1alpha1"
kind: MachineDeployment
metadata:
  name: test-pool-anexia-a
  namespace: kube-system
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      name: test-pool-anexia-a
  template:
    metadata:
      labels:
        name: test-pool-anexia-a
    spec:
      providerSpec:
        value:
          cloudProvider: "anexia"
          sshPublicKeys:
            - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAINj7wN//I+Tnuo+zbU8Z33g9SshMGconw7XYGLEFghSU"
          cloudProviderSpec:
            # token: << ANEXIA_TOKEN >>
            vlanID: "4744843577bd4b82bd98ae7c67a0e68f"
            # ubuntu: 
            # templateID: "44b38284-6adb-430e-b4a4-1553e29f352f"
            # flatcar:
            templateID: 12c28aa7-604d-47e9-83fb-5f1d1f1837b3
            locationID: "b164595577114876af7662092da89f76"
            cpus: 4
            memory: 4096
            diskSize: 10
          operatingSystem: "flatcar"
          operatingSystemSpec:
            distUpgradeOnBoot: false
            disableAutoUpdate: true
      versions:
        kubelet: "1.19.1"
